import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ja">
      <body>
        <header className="bg-sky-100">
          <a href="/" className="href">
            トップ
          </a>
          <a href="/boxmodel" className="href">
            ボックス
          </a>
        </header>
        <main>{children}</main>
      </body>
    </html>
  );
}
